version: 2.1
workflows:
  version: 2
  lint-test-build-e2e:
    jobs:
      - lint
      # - test:
      #     requires:
      #       - lint
      #     filters:
      #       branches:
      #         only:
      #           - development
      #           - master
      # - build:
      #     requires:
      #       - lint
      #     filters:
      #       branches:
      #         only: master
      # - e2e:
      #     requires:
      #       - build
      #     filters:
      #       branches:
      #         only: master

jobs:
  lint:
    machine: true

    working_directory: ~/probono-web

    steps:
      - checkout

      - run:
          name: Install Node Version Manager
          command: |
            curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
            export NVM_DIR="/opt/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
            nvm install v8.12.0
            nvm alias default v8.12.0
            echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
            echo "[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"" >> $BASH_ENV
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install Dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Lint Files
          command: npm run lint
  # build:
  # test:
  # e2e:
      
